name = "assemblyscript-compiler"
main = "src/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[build]
command = "node build.mjs"

[wasm_modules]
binaryen = "binaryen.wasm"
